site_name: Introdução ao IFC
use_directory_urls: false

copyright: Copyright &copy; 2025 Fernando Ribeiro - Bruno Leão

theme:
  features:
    #- navigation.sections
    - toc.integrate
    #- navigation.tabs
  name: material   
  language: en-custom
  custom_dir: docs\overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


site_url: "https://255ribeiro.github.io/intro_ifc/"
repo_url: "https://github.com/255ribeiro/intro_ifc/"
repo_name: "255ribeiro/intro_ifc" 

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - toc:
      toc_depth: 1

extra_css:
  - overrides/css/extra_css.css

plugins:
  - mkdocs-jupyter


