[workspace]
authors = ["Fernando Ferraz Ribeiro <ffribeiro@gmail.com>"]
channels = ["conda-forge"]
name = "intro_ifc"
platforms = [
            "win-64", 
            "linux-64", 
            "osx-64", 
            "osx-arm64",
                ]

version = "0.1.0"

[tasks]
srvdoc = "zensical serve"
blddoc = "zensical gh-deploy"

[dependencies]
ipykernel = ">=6.29.5,<7"
zensical = ">=0.0.31,<0.0.32"
ifcopenshell = "==0.8.4"
