[project]

site_name = "Introdução ao IFC e ao OpenBIM"
site_url = "https://255ribeiro.github.io/intro_ifc/"

repo_url = "https://github.com/255ribeiro/intro_ifc"
repo_name = "255ribeiro/intro_ifc"

site_description = "Anotações de aula para sobre IFC e OpenBIM"
site_author = "Fernando Ferraz Ribeiro"

copyright = """
Copyright &copy; 2026 The authors
"""

# extra_css = ["overrides/css/extra_css.css"]
# extra_javascript = [
#     "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js",  # 1st - the library
#     "javascripts/download_zip_folder.js"                                 # 2nd - your code that uses it
# ]

nav = [
  {"Home" = "index.md"},
  {"Instalação das ferramentas" = [
    {"Bonsai BIM" = "install_tools/bonsai_install/bonsai_install.md"},
    {"project libre" = "install_tools/project_libre_install/pl_install.md"},
    {"BimCollab" = "install_tools/bimcollab_install/bimcollab_install.md"},
    {"Visualizadores de IFC" = [
      {"Ifc Open Viewer" = "install_tools/open_ifc_viewer_install/open_ifc_viewer.md"},
      {"DDS Cad Viewer" = "install_tools/dds_cad_install/dds_cad_install.md"},
      {"KIT Tools" = "install_tools/kit_tools_install/kit_tools_install.md"}
    ],  icon = "<fontawesome/regula/eye"},
    {"Visualizadores Online de IFC" = "other_editors/online_ifc_viewers.md"},
  ],  icon = "fontawesome/solid/screwdriver-wrench"},
  {"BEP" = "bep/bep-bim-material.md"},


  {"Exportação IFC" = [

    {"Revit" = [
      {"IFC" = [
        {"Atualizar exportador IFC do Revit" = "exportacao/Revit/IFC/revit_IFC_install.md"},
        {"Dados do projeto" = "exportacao/Revit/IFC/ifc_project_data.md"},
        {"Configuração básica do exportador IFC do Revit" = "exportacao/Revit/config_basica/config_exporter.md"}
      ]},
      {"Informações e parâmetros" = [
        {"Organizando as pastas do projeto" = "exportacao/Revit/projeto_revit/projeto.md"},
        {"Informações do Projeto" = "exportacao/Revit/project_info.md"},
        {"Planilhas" = "exportacao/Revit/planilhas/planilhas.md"},
        {"Tipos de parâmetros" = "exportacao/Revit/parametros.md"},
        {"Parâmetros de familia" = "exportacao/Revit/param_de_familia.md"},
        {"Parâmetros compartilhados" = "exportacao/Revit/shared_param/shared_param.md"}
      ]},
      {"Georreferenciamento" = "exportacao/Revit/georref/georref.md"}
    ]},
    
    {"Archicad" = [
      {"IFC" = "exportacao/Archicad/archicad_ifc.md"}
    ]},
    
  ], icon = "fontawesome/solid/building-circle-arrow-right"}, 


  {"IFC" = [
    {"Introdução" = "IFC/ifc_intro.md"},
    {"IfcWall" = "IFC/IfcWall/IfcWall.md"},
    {"IfcCovering" = "IFC/ifcCovering/IfcCovering.md"},

  ]},

  {BonsaiBIM = [
    {"Interface" = "BonsaiBim/Aulas/AULA1_Interface_Blender_BonsaiBIM.md"},
    {"Search Groups" = "BonsaiBim/Aulas/AULA2_Search_BonsaiBIM.md"},
    {"Search Groups - referências" = "BonsaiBim/Aulas/AULA_2_search_references.md"},
    {"Merge Ifc Projects" = "BonsaiBim/merge_ifc_plus/index.md"},
    {"Quantificação" = "BonsaiBim/Aulas/AULA3_Quantificacao_BonsaiBIM.md"},

  ]},


  {"IDS" = [
    {"IDS" = "IDS/ids-bim-material.md"},
    {"IDS | editores Online" = "IDS/ids_editor.md"}
  ], icon = "fontawesome/solid/building-circle-check"},
  {"Exemplos" = "exemplos/exemplos.md"},
  {"Exercícios" = [
    {"Exercício 01" = "BCF/exercicio.md"},
    {"Exercício 02" = "IDS/exercicio/exercicio_ids.md"}
  ]},

    {BCF = [
    {"Conceito" = "BCF/bcf_basics.md"},
    

  ]},

  
  {"Clash detection" = "clash/clash-detection-material.md"},

  {"Exemplos" = "exemplos/exemplos.md"},

  {"Editais" = [
    {"Edital AV1" = "editais/edital_av1.md"},
    {"Edital AV2" = "editais/edital_av2.md"},
    {"Edital AV3" = "editais/edital_av3.md"}

  ]},

  {"Videos de apoio" = "playlist_aulas"},

]

[project.theme]
variant = "classic"
language = "pt-BR"
favicon = "fontawesome/solid/house"


features = [
    "announce.dismiss",                  # allows users to dismiss the announcement bar
    # "content.action.view",             # adds a button to view the page source
    # "content.action.edit",             # adds a button to edit the page in the repo
    "content.code.annotate",             # enables annotations inside code blocks
    "content.code.copy",                 # adds a copy button to code blocks
    "content.code.select",               # adds a line range selection button to code blocks
    "content.footnote.tooltips",         # renders footnotes as inline tooltips
    "content.tabs.link",                 # syncs all content tabs with the same label
    "content.tooltips",                  # enables tooltips on links
    # "header.autohide",                 # hides header when scrolling down
    # "navigation.expand",               # expands all nav sections by default
    # "navigation.footer",               # adds prev/next page links in footer
    # "navigation.indexes",              # attaches index.md to section headers
    "navigation.instant",                # enables instant navigation via XHR
    "navigation.instant.prefetch",       # prefetches pages on link hover
    "navigation.instant.progress",       # shows progress bar on slow connections
    "navigation.path",                   # shows breadcrumb above page title
    # "navigation.prune",                # only renders visible nav items (reduces size)
    # "navigation.sections",             # renders top-level sections as flat groups
    # "navigation.tabs",                 # renders top-level sections as header tabs
    # "navigation.tabs.sticky",          # keeps tabs visible while scrolling
    "navigation.top",                    # shows back-to-top button
    "navigation.tracking",               # updates URL with active anchor
    "search.highlight",                  # highlights search terms after following result
    "search.share",                      # adds a share button to search results
    "search.suggest",                    # shows search suggestions while typing
    "toc.follow",                        # auto-scrolls TOC to active anchor
    # "toc.integrate",
    "content.footnote.tooltips"                  # moves TOC into the left navigation sidebar
]

[project.theme.icon]
logo = "fontawesome/regular/house"

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "lucide/sun-moon"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "lime"
accent = "yellow"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"


# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "lime"
accent = "yellow"
toggle.icon = "lucide/moon"
toggle.name = "Switch to system preference"

[project.markdown_extensions]
attr_list = {}
md_in_html = {}
pymdownx.blocks.caption = {}

[project.markdown_extensions.footnotes]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.toc]
toc_depth = 1

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/255ribeiro"
name = "GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/in/fernando-ferraz-ribeiro-b49a7bb0/"
name = "LinkedIn"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@ferrax"
name = "youtube"

[[project.extra.social]]
icon = "fontawesome/solid/envelope"
link = "mailto:ffribeiro@gmail.com"
name = "Email"